[emulator]
ram_size = 1048576  # 1MB
log_level = "info"  # debug, info, warn, error
log_file = "emulator.log"
log_format = "[{level}] {timestamp} - {message}"
log_timestamp = "%Y-%m-%d %H:%M:%S"
boot_delay = 100  # milliseconds
enable_breakpoints = true

[disk]
image_path = "c_drive"
write_protect = false
geometry = "auto"  # auto, custom
cylinders = 1024   # used if geometry = "custom"
heads = 16
sectors = 63
sector_size = 512

[serial.com1]
enabled = true
baud_rate = 9600
data_bits = 8
stop_bits = 1
parity = "none"  # none, odd, even, mark, space
flow_control = "none"  # none, hardware, software, both
fifo_enabled = true
fifo_trigger_level = 14  # 1, 4, 8, 14 bytes
dtr_on_boot = true
rts_on_boot = true
log_traffic = true

[serial.com2]
enabled = false
# ... same options as com1

[serial.com3]
enabled = false
# ... same options as com1

[serial.com4]
enabled = false
# ... same options as com1

[monitor]
history_size = 100
prompt = "> "
color_enabled = true
default_memory_rows = 8
default_memory_cols = 16
auto_refresh = false
refresh_interval = 1000  # milliseconds
save_history = true
history_file = ".monitor_history"

[debug]
trace_instructions = false
trace_interrupts = true
trace_io = true
break_on_int = []  # list of interrupt numbers to break on
break_on_io = []   # list of I/O ports to break on
initial_breakpoints = []  # list of addresses to set breakpoints at startup 